---
- name: Desktop provisioning
  hosts: all
  roles:
        - common
        - audio
        - comms
        - develop
        - gui
        - network
        - user
        - utils
        - video
        - web
